config/routes.rb
Rails.application.routes.draw do
  resources :articles, only: [:show] do
    resources :comments
  end

  root 'articles#index'

  namespace :admin do
    root 'articles#index'
    
    get 'signin' => 'sessions#new'
    post 'signin' => 'sessions#create'
    delete 'signout' => 'sessions#destroy'

    resources :articles, except: [:show] do
      collection do
        post :preview
      end
    end
    resources :categories, except: [:show]
  end

end

app/models/article.rb
class Article < ActiveRecord::Base
	has_and_belongs_to_many :categories
	accepts_nested_attributes_for :categories

	has_many :comments, dependent: :destroy
	validates :title, presence: true,
										length: { minimum: 5 }

	scope :recent, -> { where('created_at > ?', 10.days.ago )}

	scope :search, -> (keyword){
	 where("title LIKE ? OR text LIKE ?", "%#{keyword}%", "%#{keyword}%") if keyword.present? 
	}

	scope :filter_category, -> (category_name){
	 joins(:categories).where('categories.name = ?', category_name) if category_name.present?
	}

	scope :filter_archive, -> (article_date){
		where("strftime('%Y-%m', created_at) = ?", article_date) if article_date.present?
	}
end

app/controllers/admin/articles_controller.rb
class Admin::ArticlesController < AdminController

	# http_basic_authenticate_with name: 'admin', password: 'admin', except: [:show]
	before_action :get_categories, only: [:show, :index]

	def new
		@article = Article.new
		@article.categories.build		
	end

	def create
		@article = Article.new(article_params_basic)

		create_update_categories

		if @article.save
			flash[:success] = "创建日志成功"
      redirect_to admin_articles_path
		else
			flash.now[:danger] = "创建日志失败"
      render "new"
		end
	end

	def index
		@articles_grid = initialize_grid(Article,
			include: [:categories],
			order: "created_at",
			order_direction: "desc"
			)
	end

	def edit
		@article = Article.find(params[:id])
		@article.categories.build if @article.categories.blank?
	end

	def update
		@article = Article.find(params[:id])
		
		create_update_categories

		if @article.update(article_params_basic)
			flash[:success] = "更新日志成功"
			redirect_to admin_articles_path
		else
			flash[:danger] = "更新日志失败"
			render 'edit'	
		end
	end

	def destroy
		@article = Article.find(params[:id])

    if @article.destroy
      flash[:success] = "日志删除成功"
    else
      flash[:danger] = "日志删除失败"
    end

    redirect_to admin_articles_path
	end

  def preview
		@text = params[:data]
		# logger.info("ssddd..." + @body)
		# render json: @body
	end

	private
	def article_params_basic
		params.require(:article).permit(:title, :text)
	end
	def article_params
		params.require(:article).permit(:title, :text, 														
																		 :categories_attributes => [:id, :name])
	end

	def get_categories
		@category = Category.all
	end

	def create_update_categories
		@article.categories.clear
		article_params["categories_attributes"].each_value do |category_arr|
			categories = category_arr["name"].strip.split(',')
			categories.each do |category|
				if @category = Category.find_by_name(category.strip)
					@article.categories << @category
				else
					@category = Category.create(name: category.strip)
					@article.categories << @category
				end
			end
		end
	end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

	# http_basic_authenticate_with name: 'admin', password: 'admin', except: [:index, :show]
	before_action :get_categories, except: [:update, :destroy]

	def index
		# @article = Article.all 
		@article = Article.order(created_at: :desc)
											.search(params[:keyword])
											.filter_category(params[:filter_category])
											.filter_archive(params[:filter_archive])
											.paginate(page: params[:page], per_page: 8)
											
	end

	def show
		@article = Article.find(params[:id])
	end

	private
		def get_categories
			@category = Category.all
		end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/admin/articles/_form.html.erb
<%= form_for [:admin, @article] do |f| %>

<div class="form-group">
	<%= f.label :title, "标题" %>
	<%= f.text_field :title, class: "form-control" %>
</div>

<%= f.fields_for :categories do |c| %>
	<div class="form-group">
		<%= c.label :name, "分类" %>
		<%= c.text_field :name, class: "form-control" %>
	</div>
<% end %>

<div class="form-group">
	<%= f.label :text, "正文内容" %>
	<div class="blog_content_editor_tab clearfix">
    <%= link_to "编辑", "#", id: "article_edit" %>
    <%= link_to "预览", "#", id: "article_preview" %>
  </div>
  <div id="article_edit_div">
		<%= f.text_area :text, class: "form-control", rows: 15 %>
	</div>
  <div id="article_preview_div" class="context" style="display:none">
  	<%= text_area :article_preview, :text, class: "form-control", rows:15 %>
  </div>
  <!-- <div>
    [<a href="http://wowubuntu.com/markdown/" target="_blank">Markdown中文帮助</a>]
    [<a href="https://help.github.com/articles/github-flavored-markdown" target="_blank">Github风格的Markdown格式</a>]
  </div> -->
</div>

<div class="form-group">
	<%= f.submit "添加", class: "btn btn-primary col-xs-2 pull-right" %>
</div>

<% end %>

app/views/admin/articles/edit.html.erb
<h3 class="form-title">编辑日志 <%= @article.title %></h3>

<%= render 'form' %>

app/views/admin/articles/edit.js.erb
$('#article_edit_div').show();
$('#article_preview_div').hide();

app/views/admin/articles/index.html.erb
<% content_for :page_title do %>日志管理<% end %>

<%= grid(@articles_grid) do |g|

  g.column name: "ID", attribute: "id" do |article|
    article.id
  end

  g.column name: "标题", attribute: "title" do |article|
    article.title
  end

  g.column name: "分类", attribute: "name", model: "Category" do |article|
    article.categories.map { |c| c.name }.join(" ")

  end

  g.column name: "创建日期", attribute: "created_at" do |article|
    article.created_at.strftime("%Y-%m-%d %H:%m")
  end

  g.column do |article|
    link_to("编辑", edit_admin_article_path(article), class: "btn btn-default btn-xs") +
    link_to("删除", admin_article_path(article), method: :delete, class: "btn btn-danger btn-xs")
  end

end -%>

app/views/admin/articles/new.html.erb
<h3 class="form-title">添加新日志</h3>
<%= render 'form' %>