config/routes.rb
Rails.application.routes.draw do
  resources :articles, only: [:show] do
    resources :comments
  end

  root 'articles#index'

  namespace :admin do
    root 'articles#index'
    
    get 'signin' => 'sessions#new'
    post 'signin' => 'sessions#create'
    delete 'signout' => 'sessions#destroy'

    resources :articles, except: [:show] do
      collection do
        post :preview
      end
    end
    resources :categories, except: [:show]
  end

end

app/models/category.rb
class Category < ActiveRecord::Base
	has_and_belongs_to_many :articles
	validates :name, uniqueness: true
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < AdminController

	def index
		@categories_grid = initialize_grid(Category,
			order: "created_at",
			order_direction: "desc"
			)
	end

	def edit
		@category = Category.find(params[:id])
	end

	def update
		@category = Category.find(params[:id])

		if @category.update(category_params)
			flash[:success] = "更新日志成功"
			redirect_to admin_categories_path
		else
			flash[:danger] = "更新日志失败"
			render 'edit'	
		end
	end


	def destroy
		@category = Category.find(params[:id])

    if @category.destroy
      flash[:success] = "类目删除成功"
    else
      flash[:danger] = "类目删除失败"
    end

    redirect_to admin_categories_path
	end

	private
		def category_params
			params.require(:category).permit(:name)
		end
end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/admin/categories/edit.html.erb
<h3 class="form-title">编辑类目 <%= @category.name %></h3>

<%= form_for [:admin, @category] do |f| %>

<div class="form-group">
	<%= f.label :name, "名称" %>
	<%= f.text_field :name, class: "form-control" %>
</div>

<div class="form-group">
	<%= f.submit "添加", class: "btn btn-primary col-xs-2 pull-right" %>
</div>

<% end %>

app/views/admin/categories/index.html.erb
<% content_for :page_title do %>日志类目<% end %>

<%= grid(@categories_grid) do |g|

  g.column name: "ID", attribute: "id" do |category|
    category.id
  end

  g.column name: "名称", attribute: "name" do |category|
    category.name
  end

  g.column name: "创建日期", attribute: "created_at" do |category|
    category.created_at.strftime("%Y-%m-%d %H:%m")
  end

  g.column do |category|
    link_to("编辑", edit_admin_category_path(category), class: "btn btn-default btn-xs") +
    link_to("删除", admin_category_path(category), method: :delete, class: "btn btn-danger btn-xs")
  end

end -%>