config/routes.rb
Rails.application.routes.draw do
  resources :articles, only: [:show] do
    resources :comments
  end

  root 'articles#index'

  namespace :admin do
    root 'articles#index'
    
    get 'signin' => 'sessions#new'
    post 'signin' => 'sessions#create'
    delete 'signout' => 'sessions#destroy'

    resources :articles, except: [:show] do
      collection do
        post :preview
      end
    end
    resources :categories, except: [:show]
  end

end

app/models/article.rb
class Article < ActiveRecord::Base
	has_and_belongs_to_many :categories
	accepts_nested_attributes_for :categories

	has_many :comments, dependent: :destroy
	validates :title, presence: true,
										length: { minimum: 5 }

	scope :recent, -> { where('created_at > ?', 10.days.ago )}

	scope :search, -> (keyword){
	 where("title LIKE ? OR text LIKE ?", "%#{keyword}%", "%#{keyword}%") if keyword.present? 
	}

	scope :filter_category, -> (category_name){
	 joins(:categories).where('categories.name = ?', category_name) if category_name.present?
	}

	scope :filter_archive, -> (article_date){
		where("strftime('%Y-%m', created_at) = ?", article_date) if article_date.present?
	}
end

app/models/category.rb
class Category < ActiveRecord::Base
	has_and_belongs_to_many :articles
	validates :name, uniqueness: true
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :article
  validates :commenter, presence: true, length: { maximum: 50 }
  validates :body, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
	before_create :create_remember_token

	has_secure_password

	def User.new_remember_token
		SecureRandom.urlsafe_base64
	end

	def User.hash(token)
		Digest::SHA1.hexdigest(token)
	end

	private
		def create_remember_token
			self.remember_token = User.hash(User.new_remember_token)
		end
end

app/controllers/admin/admin_controller.rb
class Admin::AdminController < AdminController
  
  def index
  	if !signed_in?
			flash[:danger] = "需要登录授权才能访问"
    	redirect_to admin_signin_path
		end
  end

end

app/controllers/admin_controller.rb
class AdminController < ActionController::Base
	# protect_from_forgery with: :exception
  protect_from_forgery with: :null_session
	
	layout 'admin'
	include SessionsHelper

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # protect_from_forgery with: :exception
  protect_from_forgery with: :null_session
  include SessionsHelper
  
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

	# http_basic_authenticate_with name: 'admin', password: 'admin', except: [:index, :show]
	before_action :get_categories, except: [:update, :destroy]

	def index
		# @article = Article.all 
		@article = Article.order(created_at: :desc)
											.search(params[:keyword])
											.filter_category(params[:filter_category])
											.filter_archive(params[:filter_archive])
											.paginate(page: params[:page], per_page: 8)
											
	end

	def show
		@article = Article.find(params[:id])
	end

	private
		def get_categories
			@category = Category.all
		end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

	http_basic_authenticate_with name: 'admin', password: 'admin', only: :destroy
	
	def create
		@article = Article.find(params[:article_id])
		@comment = @article.comments.new(comment_params)
		if @comment.save
			flash[:success] = "successful."
		else
			flash[:danger] = "faild."
		end
		redirect_to article_path(@article)

	end

	private
		def comment_params
			params.require(:comment).permit(:commenter, :body)
		end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def index
		
	end
  def new
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
require "redcarpet"

module ApplicationHelper
	
	def sanitize_topic(body)
    sanitize body, :tags => %w(p br img h1 h2 h3 h4 blockquote pre code b i strong em strike del u a ul ol li span), :attributes => %w(href src class title alt target rel)
  end

  # Returns the full title on a per-page basis.
	def full_title(page_title)
		base_title = "Shawn's Blog"
		if page_title.empty?
			base_title
		else
			"#{base_title} | #{page_title}"
		end
	end

# 日志归档
	def archive
		if !Article.all.empty?

		@mintime = Article.first.created_at.strftime('%Y-%m') 
		@maxtime = Article.last.created_at.strftime('%Y-%m') 
		@mintime..@maxtime

		end
	end

	def markdown(str, options = {})
    # XXX: the renderer instance should be a class variable

    options[:hard_wrap] ||= false
    options[:class] ||= ''
    assembler = Redcarpet::Render::HTML.new(:hard_wrap => options[:hard_wrap]) # auto <br> in <p>

    renderer = Redcarpet::Markdown.new(assembler, {
      :autolink => true,
      :fenced_code_blocks => true
    })
    content_tag(:div, sanitize(MarkdownConverter.convert(str)), :class => options[:class])
  end

end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

	def sign_in(user)
		remember_token = User.new_remember_token
		cookies.permanent[:remember_token] = remember_token
		user.update_attribute(:remember_token, User.hash(remember_token))
		self.current_user = user
	end

	def signed_in?
		!current_user.nil?	
	end

	def current_user=(user)
		@current_user = user
	end

	def current_user
		remember_token = User.hash(cookies[:remember_token])
		@current_user ||= User.find_by(remember_token: remember_token)
	end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_archive.html.erb
<% if !Article.all.empty? %>
<form>
	<div class="list-group">
		<a class="list-group-item active">文章归档</a>  
		<% archive.each do |date| %>
		<%= link_to date, { action: "index", filter_archive: date }, class: "list-group-item" %>
		<% end %>		
	</div> 
</form>
<% end %>

app/views/layouts/_category.html.erb
<!-- Blog Categories Well -->
<!-- <div class="well"> -->

<form>
  <div class="list-group">
    <a class="list-group-item active">分类目录</a>  
    <% @category.each do |category| %>
      <%= link_to category.name,  { action: "index" , filter_category: category.name }, 
                class: "list-group-item" %>    
    <% end %>
  </div>
  <!-- </div> -->
</form>

app/views/layouts/_footer.html.erb
<footer>
    <div class="row">
        <div class="col-lg-12">
            <p>Copyright &copy; Shawn 2014</p>
        </div>
    </div>
</footer>

app/views/layouts/_header.html.erb
 <!-- <header> -->
    <!-- Navigation -->
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <%= link_to "Shawn's Blog", root_path, class: "navbar-brand" %>
                <!-- <a class="navbar-brand" href="#">Shawn's Blog</a> -->
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
          <!--   <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <% @category.each do |category| %>
                    <li>
                        <a href="#"><%= category.name %></a>
                    </li>
                   <% end %>
                </ul>
            </div> -->
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>
<!-- </header> -->

app/views/layouts/_pager.html.erb
 <!-- Pager -->
 <ul class="pager">
 <!-- 	<li class="previous">
 		<a href="#">&larr; Older</a>
 	</li> -->
 	<li class="next">
 		<a href="#">More &rarr;</a>
 	</li>
 </ul>


 

app/views/layouts/_searcher.html.erb
<!-- Blog Search Well -->

  <form>

  <div class="list-group">
<!--     <a class="list-group-item active">Blog Search</a>     --> 

      <div class="form-group">
   <div class="input-group">
        <input type="text" class="form-control" value='<%= params[:keyword] %>' name='keyword' placeholder='站内搜索' >
        <span class="input-group-btn">
            <button class="btn btn-default" type="submit" >
                <span class="glyphicon glyphicon-search"></span>
            </button>
        </span>
    </div>
      </div>
      </div>
 
  </form>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/admin.html.erb
<!DOCTYPE HTML>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <title>Shawn's Blog</title>
    <%= stylesheet_link_tag    'administrator', :media => "all" %>
    <%= javascript_include_tag 'administrator' %>
    <link rel="stylesheet" href="//code.jquery.com/ui/1.11.1/themes/smoothness/jquery-ui.css">
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>

  <body>
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
     <div class="container">

      <div class="navbar-header">
        <%= link_to "Blog 后台管理", admin_articles_path, class: "navbar-brand" %>
      </div>

      <div class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
          <li class="dropdown">

            <a data-toggle="dropdown" class="dropdown-toggle" href="#"> 日志 <b class="caret"></b> </a>
            <ul class="dropdown-menu">
              <li><%= link_to "日志管理", admin_articles_path %></li>
              <li><%= link_to "添加新日志", new_admin_article_path %></li>
              <li><%= link_to "日志类目", admin_categories_path %></li>
            </ul>
          </li>

          <li class="dropdown">
            <a data-toggle="dropdown" class="dropdown-toggle" href="#"> 附件 <b class="caret"></b> </a>
            <ul class="dropdown-menu">
              <li><%= link_to "上传附件", "#" %></li>
              <li><%= link_to "附件管理", "#" %></li>
            </ul>
          </li>
        </ul>

        <ul class="nav navbar-nav">
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown"> 设置 <b class="caret"></b> </a>
            <ul class="dropdown-menu">
              <li><%= link_to "统计代码设置", "#" %></li>
            </ul>
          </li>
        </ul>

        <ul class="nav navbar-nav navbar-right">
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown"><b class="caret"></b> </a>
            <ul class="dropdown-menu">
              <li><%= link_to "网站首页", "#" %></li>
              <li><%= link_to "登出", "#", method: :delete %></li>
            </ul>
          </li>
        </ul>

      </div>
    </div>

    </nav>

    <div class="container">
      <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
      
      <%= yield %>
    </div>

    <div id="footer"></div>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>

<body>
  <%= render 'layouts/header' %>
  <!-- Page Content -->
  <div class="container">
    <div class="row">
      <!-- Blog Entries Column -->
      <div class="col-md-8">
        <!-- flash message -->
        <% flash.each do |key, value| %>
          <%= content_tag(:div, value, class: "alert alert-#{key}") %>
        <% end %>
        <!-- /.flash message -->
        <%= yield %>
        <%# render 'layouts/pager' %>               
      </div>

      <!-- Blog Sidebar Widgets Column -->
      <div class="col-md-4">
      <br>
       <%= render 'layouts/searcher' %>
       <%= render 'layouts/category' %> 
       <%= render 'layouts/archive' %> 
      </div>
    </div>
    <hr>
    <%= render 'layouts/footer' %>
  </div>
  <!-- /.container -->

</body>
</html>